version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tcpcat
    main: ./cmd/tcpcat
    binary: tcpcat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/*

nfpms:
  - id: packages
    package_name: tcpcat
    vendor: NycolazSec
    homepage: https://tcpcat.nycolazsec.com
    maintainer: NycolazSec <contact@nycolazsec.com>
    description: High-Performance Network Reconnaissance & Vulnerability Intelligence Engine
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request