package service

import (
	"crypto/tls"
	"net"
	"testing"
	"time"
)

// toItems/fromItems let the cipherMung table tests work with plain ints
// instead of byte pairs, for readability; cipherMung itself is agnostic to
// what the [][]byte payloads actually mean.
func toItems(nums []int) [][]byte {
	items := make([][]byte, len(nums))
	for i, n := range nums {
		items[i] = []byte{byte(n)}
	}
	return items
}

func fromItems(items [][]byte) []int {
	nums := make([]int, len(items))
	for i, it := range items {
		nums[i] = int(it[0])
	}
	return nums
}

// Expected outputs below were generated by running the reference
// implementation's own cipher_mung() in Python against the same [1..6]
// and [1..5] inputs (see the plan/session notes), not derived from this
// Go port -- an independent ground truth.
func TestCipherMung(t *testing.T) {
	even := []int{1, 2, 3, 4, 5, 6}
	odd := []int{1, 2, 3, 4, 5}

	tests := []struct {
		name  string
		input []int
		mode  string
		want  []int
	}{
		{"REVERSE even", even, "REVERSE", []int{6, 5, 4, 3, 2, 1}},
		{"TOP_HALF even", even, "TOP_HALF", []int{3, 2, 1}},
		{"BOTTOM_HALF even", even, "BOTTOM_HALF", []int{4, 5, 6}},
		{"MIDDLE_OUT even", even, "MIDDLE_OUT", []int{4, 3, 5, 2, 6, 1}},
		{"REVERSE odd", odd, "REVERSE", []int{5, 4, 3, 2, 1}},
		{"TOP_HALF odd", odd, "TOP_HALF", []int{3, 2, 1}},
		{"BOTTOM_HALF odd", odd, "BOTTOM_HALF", []int{4, 5}},
		{"MIDDLE_OUT odd", odd, "MIDDLE_OUT", []int{3, 4, 2, 5, 1}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := fromItems(cipherMung(toItems(tt.input), tt.mode))
			if len(got) != len(tt.want) {
				t.Fatalf("cipherMung(%v, %s) = %v, want %v", tt.input, tt.mode, got, tt.want)
			}
			for i := range got {
				if got[i] != tt.want[i] {
					t.Errorf("cipherMung(%v, %s) = %v, want %v", tt.input, tt.mode, got, tt.want)
					break
				}
			}
		})
	}
}

func TestCipherByte(t *testing.T) {
	if got := cipherByte(""); got != "00" {
		t.Errorf(`cipherByte("") = %q, want "00"`, got)
	}
	// First entry of cipherCanonicalOrder is {0x00,0x04} -> 1-indexed
	// position 1 -> "01".
	if got := cipherByte("0004"); got != "01" {
		t.Errorf(`cipherByte("0004") = %q, want "01"`, got)
	}
	// A cipher hex string absent from the canonical table falls through
	// to len(table)+1, same as the reference's unguarded loop. The table
	// has 69 entries (see jarm.go), so the fallthrough is 70 = 0x46.
	if len(cipherCanonicalOrder) != 69 {
		t.Fatalf("cipherCanonicalOrder has %d entries, want 69 (test's expected fallthrough value is stale)", len(cipherCanonicalOrder))
	}
	if got := cipherByte("ffff"); got != "46" {
		t.Errorf(`cipherByte(unknown) = %q, want "46" (70, the fallthrough count)`, got)
	}
}

func TestVersionByte(t *testing.T) {
	tests := []struct {
		version string
		want    string
	}{
		{"", "0"},
		{"0300", "a"},
		{"0301", "b"},
		{"0302", "c"},
		{"0303", "d"},
		{"0304", "e"},
		{"xx", "0"}, // too short -- defensive fallback, not present in the reference
	}
	for _, tt := range tests {
		if got := versionByte(tt.version); got != tt.want {
			t.Errorf("versionByte(%q) = %q, want %q", tt.version, got, tt.want)
		}
	}
}

func TestJarmHashAllEmptyIsZero(t *testing.T) {
	var results [10]string
	for i := range results {
		results[i] = "|||"
	}
	if got := jarmHash(results); got != jarmZeroHash {
		t.Errorf("jarmHash(all empty) = %q, want the all-zero hash", got)
	}
}

func TestJarmHashDeterministic(t *testing.T) {
	var a, b [10]string
	for i := 0; i < 10; i++ {
		a[i] = "0004|0303|h2|0017-ff01"
		b[i] = "0004|0303|h2|0017-ff01"
	}
	if jarmHash(a) != jarmHash(b) {
		t.Error("jarmHash is not deterministic for identical input")
	}
	if len(jarmHash(a)) != 62 {
		t.Errorf("jarmHash length = %d, want 62", len(jarmHash(a)))
	}
}

// startPlainTLSServer starts a real tls.Listen server (default config, so
// it negotiates whatever cipher/version each of the 10 JARM probes' offer
// actually allows) and returns its port, mirroring startTLSTestServer in
// tls_test.go but accepting all 10 of ProbeJARM's connections rather than
// just one.
func startPlainTLSServer(t *testing.T, cert tls.Certificate) int {
	t.Helper()
	ln, err := tls.Listen("tcp", "127.0.0.1:0", &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   tls.VersionTLS10,
	})
	if err != nil {
		t.Fatalf("tls.Listen: %v", err)
	}
	t.Cleanup(func() { _ = ln.Close() })

	go func() {
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			go func() {
				defer func() { _ = conn.Close() }()
				if tlsConn, ok := conn.(*tls.Conn); ok {
					_ = tlsConn.Handshake()
				}
			}()
		}
	}()

	return ln.Addr().(*net.TCPAddr).Port
}

func TestProbeJARMAgainstLocalServer(t *testing.T) {
	cert := selfSignedCert(t, "127.0.0.1", time.Now().AddDate(1, 0, 0))
	port := startPlainTLSServer(t, cert)

	info := ProbeJARM("127.0.0.1", port, 2*time.Second, "")
	if info == nil {
		t.Fatal("ProbeJARM() = nil, want a result")
	}
	if len(info.Hash) != 62 {
		t.Errorf("Hash length = %d, want 62: %q", len(info.Hash), info.Hash)
	}
	if info.Hash == jarmZeroHash {
		t.Error("Hash is all-zero against a live TLS server, want a real fingerprint")
	}

	// Same server, same config -- a second probe must produce the exact
	// same fingerprint (JARM's whole point is determinism per TLS stack).
	info2 := ProbeJARM("127.0.0.1", port, 2*time.Second, "")
	if info2.Hash != info.Hash {
		t.Errorf("Hash not deterministic across repeat probes: %q vs %q", info.Hash, info2.Hash)
	}
}

func TestProbeJARMUnreachableReturnsZeroHash(t *testing.T) {
	info := ProbeJARM("127.0.0.1", 1, 200*time.Millisecond, "")
	if info == nil {
		t.Fatal("ProbeJARM() = nil, want a result")
	}
	if info.Hash != jarmZeroHash {
		t.Errorf("Hash = %q for an unreachable port, want the all-zero hash", info.Hash)
	}
}
